### ISSUE TITLE
There's no index.js

### ISSUE THREAD

**Issue by kkgthb** [brob/eleventy-plugin-podcast-tools#8]
This plugin doesn't run -- its `package.json` says `main` is an `index.js` but there's no `index.js` installed via NPM.

**Comment by brob** [comment]
Hey Katie! This is what happens when you throw together a plugin based on a tweet and don't do proper testing! Thanks for pointing this out!

 The latest version (0.0.3) has this fixed along with a few vulnerability fixes.
